### ISSUE TITLE
Java 20 "Missing Foreign Linker API"

### ISSUE THREAD

**Issue by TheHardew** [gotson/NightMonkeys#22]
I tried to run komga with java 20, and I got this error:
```
2023-05-14 14:08:04.296  WARN 502417 --- [           main] c.g.g.n.j.i.plugins.JxlImageReaderSpi    : Missing Foreign Linker API, plugin will be disabled. Try adding JVM arguments: --enable-preview
```
I'm already using this option and everything works correctly with java 19.
This is how I launch komga:
```
~ $ cat /bin/komga
#!/bin/sh
exec /usr/bin/java --enable-preview -Dforeign.restricted=permit -jar '/usr/share/java/komga/komga.jar' "$@"
```

Am I doing something wrong?
I tried to search the web, but google can't even find one page with "Missing Foreign Linker API".

**Comment by gotson** [comment]
The foreign linker API is still in preview, it changes at each JDK.

The library requires JDK 19 for now. I don't have much time to update it to JDK 20.
