### ISSUE TITLE
Off-Heap native memory leak

### ISSUE THREAD

**Issue by JayanWarden** [gotson/NightMonkeys#55]
I am experiencing an off-heap memory leak in my test application.
When reading many images, Heap size stays well below the max heap configured for the Application (for example 4GB), but when processing many HEIF images, java commit size grows into the tens of GBs of memory. The JVM dies after a while, because it cannot allocate more memory, as well as other applications on the PC due to memory starvation of the whole system.

imageio-common-0.6.2
imageio-heif-0.6.2
imageio-core-3.10.1
libheif 1.14
OpenJDK 21.0.3.9-hotspot

It is easy to reproduce with this test program:

```
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.imageio.stream.ImageInputStream;

import com.github.gotson.nightmonkeys.heif.imageio.plugins.HeifImageReader;
import com.github.gotson.nightmonkeys.heif.imageio.plugins.HeifImageReaderSpi;

public class HEIFReadLoop {

	private HeifImageReaderSpi heifSpi = new HeifImageReaderSpi();
	private HeifImageReader reader;

	public static void main(String[] args) {
		HEIFReadLoop l = new HEIFReadLoop();
	}

	public HEIFReadLoop() {
		try {
			reader = (HeifImageReader) heifSpi.createReaderInstance();
			int counter = 0;
			while (true) {
				System.out.println("read image " + counter++);
				BufferedImage image = readHeicImage(new File("test.heic"));
			}
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}
	}

	private BufferedImage readHeicImage(File file) throws IOException {
		try (ImageInputStream input = ImageIO.createImageInputStream(file)) {
			reader.reset();
			reader.setInput(input);
			BufferedImage result = reader.read(0);
			reader.dispose();
			return result;
		}
	}

}
```

Run with -Xmx256m given a sufficiently small .heic image.
When you run this test app, Heap size stays well below 256m for a small image.
But system memory used by the java process grows by about 150m each second, untill all available system RAM is consumed.

**Comment by gotson** [comment]
I cannot reproduce, i am on a Mac.

**Comment by JayanWarden** [comment]
Interesting and slightly concerning.
I managed to build this project on Windows 11

**Comment by gotson** [comment]
I ran it with a 1440x960 HEIC file, 135 KB, it ran for over 3000 iterations and i noticed no change on the memory usage.

Is it happening only with the heif plugin, or also with webp/jxl ?

What's you version of libheif ?

**Comment by JayanWarden** [comment]
I'll need to figure out the webp read path, I'll do that when I have time.

I managed to build libheif for windows via https://github.com/Microsoft/vcpkg/
Sadly, only libheif 1.14 is available as a Windows port

**Comment by gotson** [comment]
I managed to build 1.17.5 from CI to include in my app.

The port file mentions it's on 1.17.6: https://github.com/microsoft/vcpkg/blob/master/ports/libheif/vcpkg.json

**Comment by JayanWarden** [comment]
I rebuilt with a fresh pull of the sources.
My libheif on windows is now 1.17.6

libheif.pc
Name: libheif
Description: HEIF image codec.
URL: https://github.com/strukturag/libheif
Version: 1.17.6
Requires:
Requires.private: libde265 x265

java still consumes RAM untill exhaustion with my posted test read loop on Windows.
I'll check out the webp read path soon

**Comment by gotson** [comment]
> java still consumes RAM untill exhaustion with my posted test read loop on Windows.

how many iterations does it take to exhaust the ram ? How much ram does your system have ?

**Comment by JayanWarden** [comment]
500 Iters -> java.exe at 1.5GB commit size
![grafik](https://github.com/gotson/NightMonkeys/assets/102806089/f5e2d930-841d-40b3-9121-5373db262220)

1.5k iters -> java.exe at 3.86GB commit size
![grafik](https://github.com/gotson/NightMonkeys/assets/102806089/2e019fc4-0ece-49fc-913d-c3040248bb44)

So, RAM rises pretty fast.
I have 64GB of system memory, which I can exhaust in a few minutes.
Heap Size stays as configured, right now the JVM only "uses" 77MB for the test loop app
![grafik](https://github.com/gotson/NightMonkeys/assets/102806089/e723d894-e7ca-4e07-8990-fc2daafbf4f9)

**Comment by doupeng19940218** [comment]
@JayanWarden hi,buddy!Could you give me your ddl file? I also wanna reproduce it on Windows.

**Comment by doupeng19940218** [comment]
@gotson @JayanWarden I also encounter this problem.
![20240729-104707](https://github.com/user-attachments/assets/05e64827-400e-41e7-bea4-0d7fae983872)
windows 10
imageio-common-0.6.2
imageio-heif-0.6.2
imageio-core-3.10.1
libheif 1.17.6
OpenJDK 21.0.1-hotspot

**Comment by doupeng19940218** [comment]
@gotson @JayanWarden I also encounter this problem.
![20240729-104707](https://github.com/user-attachments/assets/05e64827-400e-41e7-bea4-0d7fae983872)
windows 10
imageio-common-0.6.2
imageio-heif-0.6.2
imageio-core-3.10.1
libheif 1.17.6
OpenJDK 21.0.1-hotspot

**Comment by doupeng19940218** [comment]
After read image 1720, it ends with an error.
![image](https://github.com/user-attachments/assets/a548d785-0c42-4587-a394-8b0065bc1ca2)

**Comment by doupeng19940218** [comment]
Maybe you can add this code to avoid off-heap memory leak
![Uploading 20240730-085009.jpg…]()

**Comment by doupeng19940218** [comment]
Maybe you can add this code to avoid off-heap memory leak
![20240730-085009](https://github.com/user-attachments/assets/e40df86a-f745-4b79-ae43-843a5104306b)

**Comment by gotson** [comment]
> Maybe you can add this code to avoid off-heap memory leak ![20240730-085009](https://private-user-images.githubusercontent.com/23114662/353273790-e40df86a-f745-4b79-ae43-843a5104306b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMDM2MjAsIm5iZiI6MTcyMjMwMzMyMCwicGF0aCI6Ii8yMzExNDY2Mi8zNTMyNzM3OTAtZTQwZGY4NmEtZjc0NS00Yjc5LWFlNDMtODQzYTUxMDQzMDZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDAxMzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODM0ZDZjNzA5ZGIzZWE5NTdiNTY1OWVhOWM5ZGM0MzExNmRmYjJhMGJmZmI1ZWEzOWU2OWNjMzQ1NWQ3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ncXg81FFWezS9agGVjk6UmYQMy_Ne1bVF087wwPiiz4)

i think you're right. Did you manage to test this successfully ?

**Comment by gotson** [comment]
@doupeng19940218 @JayanWarden Can you try the 0.6.3-SNAPSHOT and confirm whether this is fixed or not ?
