### ISSUE TITLE
com.github.gotson.nightmonkeys:imageio-common:jar:0.2.0 missing ? 

### ISSUE THREAD

**Issue by maxandersen** [gotson/NightMonkeys#6]
when I add com.github.gotson.nightmonkeys:imageio-jaxl:0.2.0 I get an error about com.github.gotson.nightmonkeys:imageio-common:jar:0.2.0 missing.

I can't find it in maven central https://search.maven.org/search?q=g:com.github.gotson.nightmonkeys - maybe it was missed ?

**Comment by gotson** [comment]
My bad, it was missed in the publishing. I just published that artifact, it should be available soon.
