### ISSUE TITLE
Docs: Add clarity on native libraries?

### ISSUE THREAD

**Issue by melloware** [gotson/NightMonkeys#70]
Your docs just say make sure native libraries on are the path but what Native libraries? Can you add more detailed instructions?

Also if these are `.so` or `.dll` i have seen other libraries pack them in resources and reference them from there per OS.  Just a thought!

**Comment by gotson** [comment]
The details are in the README of each plugin, like here for webp: https://github.com/gotson/NightMonkeys/tree/main/imageio-webp

**Comment by gotson** [comment]
> Also if these are `.so` or `.dll` i have seen other libraries pack them in resources and reference them from there per OS. Just a thought!

This was needed with JNI, as you need to have a small bit of C code to link Java with existing libraries. This is not necessary with Foreign Linker API, and thus there's no need to bundle those libraries as resources. That would require compiling for various different OS and architecture, ability to detect OS/arch and unpack libraries. Those libraries are available in most package managers now, so there's no need for that.

**Comment by melloware** [comment]
Ahhh i see.  From your instuctions is this possible to use on Windows?

**Comment by gotson** [comment]
> Ahhh i see. From your instuctions is this possible to use on Windows?

yes, the CI runs tests on macOS, Linux and Windows. For Windows it may be more difficult to get the pre-packaged binaries, but you can build them using vcpkg.
